OpenLiberty/guide-microprofile-config

README.adoc
finish/CustomConfigSource.json
finish/src/main/java/io/openliberty/guides/config/CustomEmailConverter.java
finish/src/main/java/io/openliberty/guides/config/Email.java
finish/src/main/java/io/openliberty/guides/microprofile/InventoryConfig.java
finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java
finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java
finish/src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java
finish/src/main/java/io/openliberty/guides/microprofile/util/JsonMessages.java
finish/src/main/java/io/openliberty/guides/rest/PropertiesResource.java
finish/src/main/resources/META-INF/microprofile-config.properties
finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter
finish/src/test/java/it/io/openliberty/guides/microprofile/ConfigurationTest.java
finish/src/test/java/it/io/openliberty/guides/microprofile/TestUtil.java
start/CustomConfigSource.json
start/src/main/java/io/openliberty/guides/microprofile/InventoryConfig.java
start/src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java
start/src/main/resources/META-INF/microprofile-config.properties

Add custom converter part to the code and the guide

Add custom converter part to the code and the guide

---

README.adoc

Changed to "Configuring Microservices".

 Changing the title of this guide to be Configuring Microservice to resolve #14

---

README.adoc

recommended changes during review

---

finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java

Minor cleanup

---

finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
start/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
start/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
start/src/main/java/io/openliberty/guides/inventory/model/SystemData.java

OpenLiberty/guides-common#95
OpenLiberty/guides-common#137

Refactor inventory

---

finish/src/test/java/it/io/openliberty/guides/config/ConfigTestUtil.java
finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java
start/src/test/java/it/io/openliberty/guides/config/ConfigTestUtil.java

Change inventory total assertions to check http status instead

---

.travis.yml
README.adoc
finish/pom.xml
finish/resources/CustomConfigSource.json
finish/src/main/java/io/openliberty/guides/config/CustomConfigSource.java
finish/src/main/java/io/openliberty/guides/config/CustomEmailConverter.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/main/liberty/config/server.xml
finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java
start/pom.xml
start/resources/CustomConfigSource.json

* updated files to fit multipane
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated files for multipane
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* updated README
* Removed finish.adoc include from README.adoc
* Adjusting order of dependencies
* JDK 11 pom update
* Updated README for new format
* Updated README
* Updated README
* Updated README
* Updated README with [hotspot] changes
* Updated README with link in new tab changes
* Updated README
* Updated README.
* Updated README.adoc
* Updated README
* …

Multipane (#82)

---

README.adoc

Fix multipane post publish test

---

README.adoc
finish/pom.xml
finish/src/main/java/io/openliberty/guides/config/CustomConfigSource.java
finish/src/main/java/io/openliberty/guides/config/CustomEmailConverter.java
finish/src/main/java/io/openliberty/guides/config/Email.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java

Fixed hotspots and file focus

---

README.adoc
finish/pom.xml
finish/src/main/java/io/openliberty/guides/config/CustomConfigSource.java
finish/src/main/java/io/openliberty/guides/config/CustomEmailConverter.java
finish/src/main/java/io/openliberty/guides/config/Email.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/test/java/it/io/openliberty/guides/config/ConfigurationTest.java

* Fixed file link
* Updated and fixed all hotspots
* hotspot hotfix
* fix
* more fixes
* Updating licensing year

Merge qa to master: Fixed hotspots and file focus (#99)

---

README.adoc
finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java
finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
finish/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter

https://github.com/OpenLiberty/guide-microprofile-config/issues/105
https://github.com/OpenLiberty/guide-microprofile-config/issues/106
Worked with @NimG98

Hotspot tag fix for InventoryConfig.java & Service Declaration files

---

finish/pom.xml
finish/src/main/liberty/config/server.xml
start/pom.xml
start/src/main/liberty/config/server.xml

https://github.com/OpenLiberty/guides-common/issues/352
https://github.com/OpenLiberty/guides-common/issues/308
- JSON files cannot include comments therefore hotspots that reference to `CustomConfigSource.json` kept as line numbers

hotspot & name convention update

---

README.adoc

Addressed peer review feedback

---

README.adoc

- removed the [INFO] tags for test output
- checked the test output here: http://lgdev1.fyre.ibm.com:4060/guides/microprofile-config.html#running-the-tests

Updated test output

---

README.adoc
finish/pom.xml
start/pom.xml

Merge qa to master: update to mp 3.2

---

README.adoc

Update the order.

---

README.adoc
finish/src/main/webapp/index.html
start/src/main/webapp/index.html

Merge qa to master: update index.html

---

README.adoc
finish/pom.xml
finish/src/main/webapp/index.html
start/pom.xml
start/src/main/webapp/index.html

Merge qa to master: directly specify version in plugins

---

finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/test/java/it/io/openliberty/guides/config/ConfigurationIT.java
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java

- update error message in InventoryResource and update tests to reflect issue outlined here: https://github.com/OpenLiberty/guides-common/issues/243

update error msg

---

README.adoc

Added warning message thrown by test case and explaining that it is expected.

Warning message

---

.github/workflows/test.yml

Merge qa to master: Enable PR checker (#173)

---

README.adoc

add cloud-hosted guide instructions

Merge qa to master: Update README.adoc (#175)

---

README.adoc

add cd to start instruction to cloud-hosted guide

Merge qa to master: Update README.adoc (#177)
